### ISSUE TITLE
suggestion: waiting for specific story to be ready

### ISSUE THREAD

**Issue by shlomitc** [applitools/eyes-storybook#13]
I have a component which animates when rendered.

This means that it will render, animate for Xms and only then I want the test to run. This causes my test to be flaky...

Currently, only `waitBeforeScreenshots` configuration is possible, but this means that all of my tests will get slower, which is not a good idea.

I can suggest adding some predicate that checks for a condition in a page to happen.

For example, I can wrap a specific story page with `<div data-eyes-storybook="loading">...</div>` and remove it once I know the component is ready.
Then in the applitools configuration, I will have the predicate which returns a boolean 
```js
{
...
  isStoryReadyPredicate: () => !!document.querySelector('[data-eyes-storybook="loading"]')
...
}
```

what do you think?

**Comment by FinestV** [comment]
#14 @shlomitc I've raised this PR which should address your use case as well

**Comment by danielschwartz85** [comment]
@shlomitc - sorry for the late response.
Look like @shlomitc PR should include a solution for this is issue.
Checking the PR will update.

Tnx for raising this 👍
