### ISSUE TITLE
Error "URL is not defined" when using storybookUrl config param

### ISSUE THREAD

**Issue by jonathan-stone** [applitools/eyes-storybook#18]
It appears that in 2.7.11 a call to the Node `URL` module was added.
When `eyes-storybook` runs, `URL` is not defined, so the script exits without running any tests.

Error is caused by this line of code:
https://github.com/applitools/eyes-storybook/blob/c014bdbe4953f3a2749c7b66bbb382fc73427668/src/getStorybookBaseUrl.js#L4

Steps to reproduce:
Install the tutorial repo
On the command line, `export APPLITOOLS_API_KEY=<Your valid key>`
Run `npx eyes-storybook` once just to ensure that all is working as expected
Run `npx @applitools/eyes-storybook@2.7.11 --storybookUrl http://whatever` 
(Note, it does not matter what you set --storybookUrl to - any string will cause this)

Expected behavior:
If you have Storybook running in another command window, it runs your tests; otherwise it attempts to run your tests and says it couldn't find any.

Actual behavior:
Outputs `URL is not defined`

Log output - not that I think you will need it:
```
Downloading Chromium r672088 - 108 Mb [====================] 100% 0.0s
Using @applitools/eyes-storybook version 2.7.11.

2019-07-04T08:01:23Z Eyes: [LOG    ] {} (): Running with the following config:
concurrency           : 10
storybookPort         : 9000
storybookHost         : localhost
storybookConfigDir    : .storybook
storybookUrl          : http://whatever
storybookStaticDir    : undefined
showStorybookOutput   : false
waitBeforeScreenshots : 50
tapFilePath           : undefined
showLogs              : true
apiKey                : secret!
appName               : tutorial-storybook-react
batchName             : tutorial-storybook-react
agentId               : eyes-storybook/2.7.11

2019-07-04T08:01:23Z Eyes: [LOG    ] {} (): eyesStorybook started
URL is not defined
```

**Comment by danielschwartz85** [comment]
Fixed in 2.7.13. 
Thanks for raising this 👍
