### ISSUE TITLE
Configure waitBeforeScreenshots per story

### ISSUE THREAD

**Issue by jonathanadler** [applitools/eyes-storybook#27]
Hello,

I was wondering if it was possible to add the `waitBeforeScreenshots` config property, to the per component configuration.

We have many tests where we need to wait for the component until it's ready for the snapshot to be taken.
However, it's usually not the case for all the tests.

And so we were wondering if it was possible to configure this for each test separately.
(and of course leaving the global configuration as well).

Thanks!

(related to  applitools/eyes-storybook#13)

**Comment by danielschwartz85** [comment]
@jonathanadler yes, sound like a good idea; will update here once I have some news about this.
Thanks for the suggestion 👍

**Comment by danielschwartz85** [comment]
Ok published with 2.9.1.
Note that `waitBeforeScreenshots` was renamed to `waitBeforeScreenshot` (no `s`)
Also Note that predicate options is currently not supported (for the per story configuration).

See doc: https://github.com/applitools/eyes-storybook#waitBeforeScreenshot

**Comment by jonathanadler** [comment]
Holy moly 😮 thanks!
