### ISSUE TITLE
debug `runBefore` code

### ISSUE THREAD

**Issue by jonathanadler** [applitools/eyes-storybook#30]
Hey,

The `runBefore` property is really great.
However, sometimes the code in this part can get a bit long and complicated, and I wonder if there's a way to debug it.

Thanks

**Comment by danielschwartz85** [comment]
Hi,
Thanks for raising this and sorry for the late response.

We will consider adding something for debugging this and update, until then I suggest doing the following:

1. open you're storybook in chrome
2. select your story
2. open Dev tools
3. switch console iframe to "storybook-preview-iframe" (in console frame select) - this is you're story's frame.
4. run the following :
_either by pasting to console or adding a snippet (sources -> add snippet)_

```
const rootEl = document.getElementById('root')
const story = __STORYBOOK_CLIENT_API__.raw().find(s => s.id === __STORYBOOK_STORY_STORE__.getSelection().storyId)
// now run your runBefore function:
runBefore({rootEl, story})
```

**Comment by jonathanadler** [comment]
Awesome I'll try that, thanks!

**Comment by danielschwartz85** [comment]
@jonathanadler note that I have edited the original script for a simpler solution ( you can click your story and then run the ```runBefore``` function )

**Comment by amitzur** [comment]
This repository is going to be archived and moved into the monorepo of all Applitools SDK's.
For new issues on this SDK, please file them at https://github.com/applitools/eyes.sdk.javascript1
