### ISSUE TITLE
Dependency on eyes.storybook node modules being installed directly from within the node_modules\@applitools\eyes.storybook directory

### ISSUE THREAD

**Issue by FinestV** [applitools/eyes-storybook#5]
This change to get the Storybook package version which was introduced recently https://github.com/applitools/eyes-storybook/commit/ef1b4cd6dafe4ef4ced70dacf2faaaf8e60a2ed2#diff-ffc54b688c373955b55f9c9dac675f52R9 relies on the presence of a package.json at the path `\node_modules\@applitools\eyes.storybook\node_modules\@storybook\react\package.json`

As a consumer of the eyes.storybook library running `npm install` from my app directory will not install these child modules under `node_modules\@applitools\eyes.storybook` so the package.json is not found and eyes.storybook fails with error: 
`Error: ENOENT: no such file or directory, open '<My App>\node_modules\@applitools\eyes.storybook\node_modules\@storybook\react\package.json'`

To work around this i need to add a postinstall step to run `npm install` directly in the eyes.storybook module directory `"postinstall": "cd node_modules\\@applitools\\eyes.storybook && npm install"`

This adds another 60-70 secs of overhead to do a second npm install when doing a clean run.

As the code is trying to just find a package version number for display is there another way this could work or if not could it possibly be dropped altogether?

Note: I have also raised a PR to move this code from const to a function as this currently causes a failure even when using a storybookUrl and not the storybookServer [Move getting the storybook package version from a const to a function](https://github.com/applitools/eyes-storybook/pull/4)

**Comment by danielschwartz85** [comment]
Hi, Thanks for the issue and sorry for the late response.
Should be fixed by now (from v2.3.7).

[0ef9abf](https://github.com/applitools/eyes-storybook/commit/0ef9abfb28dc661931c202a76a90666958f4766e)
